services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
      - bridge

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=extrastaff360
      - DB_USERNAME=segzdee
      - DB_PASSWORD=kiyingi8844
    depends_on:
      - mysql

  bridge:
    build:
      context: ./bridge
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./bridge:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=extrastaff360
      - MYSQL_USER=segzdee
      - MYSQL_PASSWORD=kiyingi8844
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

volumes:
  mysql_data:
