services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../deployment/dockerfiles/Dockerfile.frontend
    ports:
      - "3001:3000"
    networks:
      - extra360_network

  backend:
    build:
      context: ../backend
      dockerfile: ../deployment/dockerfiles/Dockerfile.backend
    ports:
      - "8000:8000"
    networks:
      - extra360_network

  bridge:
    build:
      context: ../bridge
      dockerfile: ../deployment/dockerfiles/Dockerfile.bridge
    ports:
      - "5000:5000"
    networks:
      - extra360_network

networks:
  extra360_network:
    driver: bridge
