version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
      args:
        NODE_ENV: ${NODE_ENV}
    env_file: .env
    volumes:
      - frontend_build:/app/build
      - frontend_node_modules:/app/node_modules
    networks:
      - frontend_network
      - backend_network
    deploy:
      resources:
        limits:
          cpus: ${FRONTEND_CPU_LIMIT}
          memory: ${FRONTEND_MEMORY_LIMIT}

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    env_file: .env
    volumes:
      - backend_data:/app/data
    networks:
      - backend_network
      - db_network
    deploy:
      resources:
        limits:
          cpus: ${BACKEND_CPU_LIMIT}
          memory: ${BACKEND_MEMORY_LIMIT}

  bridge:
    build:
      context: .
      dockerfile: bridge/Dockerfile.bridge
    env_file: .env
    volumes:
      - bridge_data:/app/data
    networks:
      - backend_network
      - bridge_network
    deploy:
      resources:
        limits:
          cpus: ${BRIDGE_CPU_LIMIT}
          memory: ${BRIDGE_MEMORY_LIMIT}

volumes:
  frontend_build:
  frontend_node_modules:
  backend_data:
  bridge_data:

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
  bridge_network:
    driver: bridge
  db_network:
    driver: bridge
