name: Quantum CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  quantum-matrix-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend, bridge]
        platform: [linux/amd64, linux/arm64]
    
    steps:
      - name: Initialize Quantum Context
        uses: actions/checkout@v4

      - name: Execute Docker Registry Authentication
        uses: docker/login-action@v3
        with:
          username: extrastaff360
          password: ${{ secrets.DOCKER_PAT }}

      - name: Configure BuildX Matrix
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "extrastaff360/extra360-x2"
          install: true

      - name: Execute Build Matrix
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.service }}/Dockerfile.${{ matrix.service }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            extrastaff360/extra360-${{ matrix.service }}:${{ github.sha }}
            extrastaff360/extra360-${{ matrix.service }}:latest
          cache-from: type=registry,ref=extrastaff360/extra360-${{ matrix.service }}:cache
          cache-to: type=registry,ref=extrastaff360/extra360-${{ matrix.service }}:cache,mode=max
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}
